from app.modules.authorization.module_permissions import ModulePermissionDefinition
from app.modules.authorization.models import PermissionRisk


INDIA_PERMISSION_DEFINITIONS: tuple[ModulePermissionDefinition, ...] = (
    ModulePermissionDefinition("procurement.module.view", "procurement", "module", "view", "Access procurement workflows.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("procurement.requisition.view", "procurement", "requisition", "view", "View purchase requisitions.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("procurement.requisition.create", "procurement", "requisition", "create", "Create purchase requisitions.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("procurement.requisition.manage", "procurement", "requisition", "manage", "Edit draft requisitions and lines.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.requisition.submit", "procurement", "requisition", "submit", "Submit requisitions for approval.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.requisition.approve", "procurement", "requisition", "approve", "Approve or reject purchase requisitions.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("procurement.purchase_order.view", "procurement", "purchase_order", "view", "View purchase orders.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.purchase_order.create", "procurement", "purchase_order", "create", "Create draft purchase orders.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.purchase_order.manage", "procurement", "purchase_order", "manage", "Edit purchase order lines and terms.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.purchase_order.submit", "procurement", "purchase_order", "submit", "Submit purchase orders for approval.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.purchase_order.approve", "procurement", "purchase_order", "approve", "Approve purchase orders.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("procurement.purchase_order.issue", "procurement", "purchase_order", "issue", "Issue approved purchase orders.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("procurement.receipt.view", "procurement", "receipt", "view", "View goods receipts.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("procurement.receipt.create", "procurement", "receipt", "create", "Create goods receipt drafts.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("procurement.receipt.manage", "procurement", "receipt", "manage", "Record goods receipt quantities and dispositions.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.receipt.receive", "procurement", "receipt", "receive", "Finalize goods receipts against issued purchase orders.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("subcontracts.module.view", "subcontracts", "module", "view", "Access work orders and progress claims.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("subcontracts.contract.view", "subcontracts", "contract", "view", "View work orders and scope lines.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.contract.create", "subcontracts", "contract", "create", "Create draft work orders.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.contract.manage", "subcontracts", "contract", "manage", "Edit work-order scope and lifecycle.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.contract.submit", "subcontracts", "contract", "submit", "Submit work orders for approval.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.contract.approve", "subcontracts", "contract", "approve", "Approve work orders.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("subcontracts.contract.issue", "subcontracts", "contract", "issue", "Issue approved work orders.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("subcontracts.claim.view", "subcontracts", "claim", "view", "View subcontractor progress claims.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.claim.create", "subcontracts", "claim", "create", "Create subcontractor progress claims.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.claim.manage", "subcontracts", "claim", "manage", "Edit draft progress-claim lines.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.claim.submit", "subcontracts", "claim", "submit", "Submit progress claims for certification.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.claim.certify", "subcontracts", "claim", "certify", "Certify or reject progress claims.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("subcontracts.claim.payment", "subcontracts", "claim", "payment", "Record operational payment state for certified claims.", PermissionRisk.CRITICAL),
)
