from dataclasses import dataclass

from app.modules.authorization.models import PermissionRisk


@dataclass(frozen=True, slots=True)
class ModulePermissionDefinition:
    key: str
    module: str
    resource: str
    action: str
    description: str
    risk: PermissionRisk = PermissionRisk.LOW


MODULE_PERMISSION_DEFINITIONS: tuple[ModulePermissionDefinition, ...] = (
    ModulePermissionDefinition("safety.module.view", "safety", "module", "view", "Access Safety, Inspections, and Punch within authorized projects.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("safety.record.view", "safety", "record", "view", "View permitted safety records and corrective actions.", PermissionRisk.HIGH),
    ModulePermissionDefinition("safety.record.create", "safety", "record", "create", "Create project safety records.", PermissionRisk.HIGH),
    ModulePermissionDefinition("safety.record.update", "safety", "record", "update", "Update open safety records and corrective actions.", PermissionRisk.HIGH),
    ModulePermissionDefinition("safety.record.close", "safety", "record", "close", "Close resolved safety records.", PermissionRisk.HIGH),
    ModulePermissionDefinition("safety.record.manage", "safety", "record", "manage", "Perform controlled safety-record administration.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("safety.inspection.view", "safety", "inspection", "view", "View inspection templates and project inspection runs.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("safety.inspection.create", "safety", "inspection", "create", "Create project inspection runs.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("safety.inspection.execute", "safety", "inspection", "execute", "Record and submit inspection results.", PermissionRisk.HIGH),
    ModulePermissionDefinition("safety.inspection.review", "safety", "inspection", "review", "Approve or reject inspections through shared Workflow.", PermissionRisk.HIGH),
    ModulePermissionDefinition("safety.inspection.manage", "safety", "inspection", "manage", "Create, publish, and retire inspection templates.", PermissionRisk.HIGH),
    ModulePermissionDefinition("safety.punch.view", "safety", "punch", "view", "View Punch items within the authorized project.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("safety.punch.create", "safety", "punch", "create", "Create Punch items within the authorized project.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("safety.punch.update", "safety", "punch", "update", "Update open Punch items.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("safety.punch.close", "safety", "punch", "close", "Close completed Punch items.", PermissionRisk.HIGH),
    ModulePermissionDefinition("safety.punch.manage", "safety", "punch", "manage", "Perform controlled Punch administration.", PermissionRisk.HIGH),
    ModulePermissionDefinition("equipment.module.view", "equipment", "module", "view", "Access Equipment and Materials within permitted company and projects.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("equipment.asset.view", "equipment", "asset", "view", "View company equipment assets.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("equipment.asset.manage", "equipment", "asset", "manage", "Create, update and retire company equipment assets.", PermissionRisk.HIGH),
    ModulePermissionDefinition("equipment.assignment.view", "equipment", "assignment", "view", "View project equipment assignments.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("equipment.assignment.manage", "equipment", "assignment", "manage", "Assign and release equipment within authorized projects.", PermissionRisk.HIGH),
    ModulePermissionDefinition("equipment.usage.view", "equipment", "usage", "view", "View authoritative project equipment usage records.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("equipment.usage.create", "equipment", "usage", "create", "Create draft project equipment usage records.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("equipment.usage.post", "equipment", "usage", "post", "Post authoritative project equipment usage records.", PermissionRisk.HIGH),
    ModulePermissionDefinition("equipment.rate.view", "equipment", "rate", "view", "View project equipment commercial cost rates.", PermissionRisk.HIGH),
    ModulePermissionDefinition("equipment.rate.manage", "equipment", "rate", "manage", "Create and retire effective-dated project equipment commercial rates.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("equipment.maintenance.view", "equipment", "maintenance", "view", "View equipment maintenance records.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("equipment.maintenance.manage", "equipment", "maintenance", "manage", "Create and manage equipment maintenance records.", PermissionRisk.HIGH),
    ModulePermissionDefinition("materials.material.view", "materials", "material", "view", "View the company material catalog.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("materials.material.manage", "materials", "material", "manage", "Create, update and retire material catalog records.", PermissionRisk.HIGH),
    ModulePermissionDefinition("materials.plan.view", "materials", "material_plan", "view", "View planned project material quantities.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("materials.plan.manage", "materials", "material_plan", "manage", "Create and revise project material plans.", PermissionRisk.HIGH),
    ModulePermissionDefinition("materials.delivery.view", "materials", "delivery", "view", "View project material deliveries.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("materials.delivery.manage", "materials", "delivery", "manage", "Create, receive, reject and correct project material deliveries.", PermissionRisk.HIGH),
    ModulePermissionDefinition("materials.consumption.view", "materials", "consumption", "view", "View project material consumption records.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("materials.consumption.create", "materials", "consumption", "create", "Create draft project material consumption records.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("materials.consumption.post", "materials", "consumption", "post", "Post authoritative project material consumption and cost snapshots.", PermissionRisk.HIGH),
    ModulePermissionDefinition("materials.inventory.view", "materials", "inventory", "view", "View project stock locations, transaction history and derived balances.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("materials.inventory.manage", "materials", "inventory", "manage", "Create and manage project material stock locations.", PermissionRisk.HIGH),
    ModulePermissionDefinition("meetings.meeting.view", "meetings", "meeting", "view", "View meetings, minutes, attendees, agenda and references in authorized projects.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("meetings.meeting.create", "meetings", "meeting", "create", "Create project meetings.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("meetings.meeting.update", "meetings", "meeting", "update", "Update non-finalized project meetings.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("meetings.meeting.manage", "meetings", "meeting", "manage", "Cancel and administratively manage project meetings.", PermissionRisk.HIGH),
    ModulePermissionDefinition("meetings.series.manage", "meetings", "series", "manage", "Create and manage recurring meeting series.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("meetings.attendee.manage", "meetings", "attendee", "manage", "Manage meeting attendees and attendance.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("meetings.agenda.manage", "meetings", "agenda", "manage", "Manage meeting agenda items.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("meetings.action.view", "meetings", "action", "view", "View assigned and project meeting action items.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("meetings.action.manage", "meetings", "action", "manage", "Create, assign and update meeting action items.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("meetings.reference.manage", "meetings", "reference", "manage", "Link permitted project records to meetings.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("meetings.minutes.manage", "meetings", "minutes", "manage", "Draft and revise meeting minutes before finalization.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("meetings.minutes.finalize", "meetings", "minutes", "finalize", "Finalize meeting minutes under configured approval rules.", PermissionRisk.HIGH),
    ModulePermissionDefinition("help.assistant.use", "help", "assistant", "use", "Use the permission-scoped Construction OS Assistant.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("help.assistant.upgrade", "help", "assistant", "upgrade_guidance", "Use installation, upgrade, migration and rollback guidance from the Construction OS Assistant.", PermissionRisk.HIGH),
    ModulePermissionDefinition("commercial.module.view", "commercial", "module", "view", "Access India commercial controls within authorized projects.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("commercial.party.view", "commercial", "party", "view", "View company parties and project party assignments.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("commercial.party.manage", "commercial", "party", "manage", "Create and maintain parties and project party assignments.", PermissionRisk.HIGH),
    ModulePermissionDefinition("commercial.wbs.view", "commercial", "wbs", "view", "View project WBS and cost-code structures.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("commercial.wbs.manage", "commercial", "wbs", "manage", "Create and revise project WBS and cost-code structures.", PermissionRisk.HIGH),
    ModulePermissionDefinition("commercial.boq.view", "commercial", "boq", "view", "View BOQs and approved commercial baselines.", PermissionRisk.HIGH),
    ModulePermissionDefinition("commercial.boq.manage", "commercial", "boq", "manage", "Create and revise draft BOQs and BOQ items.", PermissionRisk.HIGH),
    ModulePermissionDefinition("commercial.boq.approve", "commercial", "boq", "approve", "Approve a BOQ baseline and create an immutable snapshot.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("commercial.measurement.view", "commercial", "measurement", "view", "View project measurement-book entries.", PermissionRisk.HIGH),
    ModulePermissionDefinition("commercial.measurement.create", "commercial", "measurement", "create", "Record project quantities against approved BOQ items.", PermissionRisk.HIGH),
    ModulePermissionDefinition("commercial.measurement.submit", "commercial", "measurement", "submit", "Submit measured quantities for certification.", PermissionRisk.HIGH),
    ModulePermissionDefinition("commercial.measurement.certify", "commercial", "measurement", "certify", "Certify or reject submitted measured quantities.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("commercial.ra_bill.view", "commercial", "ra_bill", "view", "View RA bills and their certified measurement basis.", PermissionRisk.HIGH),
    ModulePermissionDefinition("commercial.ra_bill.create", "commercial", "ra_bill", "create", "Prepare RA bills from unbilled certified measurements.", PermissionRisk.HIGH),
    ModulePermissionDefinition("commercial.ra_bill.submit", "commercial", "ra_bill", "submit", "Submit an RA bill for certification.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("commercial.ra_bill.certify", "commercial", "ra_bill", "certify", "Certify RA bills and record payment state transitions.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("estimating.module.view", "estimating", "module", "view", "Access estimating and budget controls.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("estimating.estimate.view", "estimating", "estimate", "view", "View project estimates and rate analyses.", PermissionRisk.HIGH),
    ModulePermissionDefinition("estimating.estimate.manage", "estimating", "estimate", "manage", "Create and revise draft estimates.", PermissionRisk.HIGH),
    ModulePermissionDefinition("estimating.estimate.submit", "estimating", "estimate", "submit", "Submit project estimates for approval.", PermissionRisk.HIGH),
    ModulePermissionDefinition("estimating.estimate.approve", "estimating", "estimate", "approve", "Approve project estimates.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("estimating.rate_analysis.manage", "estimating", "rate_analysis", "manage", "Create versioned rate analyses.", PermissionRisk.HIGH),
    ModulePermissionDefinition("estimating.budget.view", "estimating", "budget", "view", "View project budget baselines.", PermissionRisk.HIGH),
    ModulePermissionDefinition("estimating.budget.manage", "estimating", "budget", "manage", "Create and revise draft project budgets.", PermissionRisk.HIGH),
    ModulePermissionDefinition("estimating.budget.approve", "estimating", "budget", "approve", "Approve a project budget baseline.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("procurement.module.view", "procurement", "module", "view", "Access procurement workflows.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("procurement.requisition.view", "procurement", "requisition", "view", "View purchase requisitions.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("procurement.requisition.create", "procurement", "requisition", "create", "Create purchase requisitions.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("procurement.requisition.manage", "procurement", "requisition", "manage", "Edit draft requisitions and lines.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.requisition.submit", "procurement", "requisition", "submit", "Submit requisitions for approval.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.requisition.approve", "procurement", "requisition", "approve", "Approve or reject purchase requisitions.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("procurement.purchase_order.view", "procurement", "purchase_order", "view", "View purchase orders.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.purchase_order.create", "procurement", "purchase_order", "create", "Create draft purchase orders.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.purchase_order.manage", "procurement", "purchase_order", "manage", "Edit purchase order lines and terms.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.purchase_order.submit", "procurement", "purchase_order", "submit", "Submit purchase orders for approval.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.purchase_order.approve", "procurement", "purchase_order", "approve", "Approve purchase orders.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("procurement.purchase_order.issue", "procurement", "purchase_order", "issue", "Issue approved purchase orders.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("procurement.receipt.view", "procurement", "receipt", "view", "View goods receipts.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("procurement.receipt.create", "procurement", "receipt", "create", "Create goods receipt drafts.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("procurement.receipt.manage", "procurement", "receipt", "manage", "Record goods receipt quantities and dispositions.", PermissionRisk.HIGH),
    ModulePermissionDefinition("procurement.receipt.receive", "procurement", "receipt", "receive", "Finalize goods receipts against issued purchase orders.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("subcontracts.module.view", "subcontracts", "module", "view", "Access work orders and progress claims.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("subcontracts.contract.view", "subcontracts", "contract", "view", "View work orders and scope lines.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.contract.create", "subcontracts", "contract", "create", "Create draft work orders.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.contract.manage", "subcontracts", "contract", "manage", "Edit work-order scope and lifecycle.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.contract.submit", "subcontracts", "contract", "submit", "Submit work orders for approval.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.contract.approve", "subcontracts", "contract", "approve", "Approve work orders.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("subcontracts.contract.issue", "subcontracts", "contract", "issue", "Issue approved work orders.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("subcontracts.claim.view", "subcontracts", "claim", "view", "View subcontractor progress claims.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.claim.create", "subcontracts", "claim", "create", "Create subcontractor progress claims.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.claim.manage", "subcontracts", "claim", "manage", "Edit draft progress-claim lines.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.claim.submit", "subcontracts", "claim", "submit", "Submit progress claims for certification.", PermissionRisk.HIGH),
    ModulePermissionDefinition("subcontracts.claim.certify", "subcontracts", "claim", "certify", "Certify or reject progress claims.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("subcontracts.claim.payment", "subcontracts", "claim", "payment", "Record operational payment state for certified claims.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("scheduling.module.view", "scheduling", "module", "view", "Access project scheduling.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("scheduling.schedule.view", "scheduling", "schedule", "view", "View schedules, activities, baselines and progress.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("scheduling.schedule.manage", "scheduling", "schedule", "manage", "Create and revise schedules, activities and dependencies.", PermissionRisk.HIGH),
    ModulePermissionDefinition("scheduling.baseline.create", "scheduling", "baseline", "create", "Create immutable project schedule baselines.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("scheduling.progress.update", "scheduling", "progress", "update", "Record project schedule progress.", PermissionRisk.HIGH),
    ModulePermissionDefinition("scheduling.schedule.complete", "scheduling", "schedule", "complete", "Complete an active project schedule.", PermissionRisk.HIGH),
    ModulePermissionDefinition("workforce.rate.view", "workforce", "rate", "view", "View permitted project worker commercial rates.", PermissionRisk.HIGH),
    ModulePermissionDefinition("workforce.rate.manage", "workforce", "rate", "manage", "Create and retire effective-dated project worker commercial rates.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.module.view", "financials", "module", "view", "Access project financial and job-cost controls.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.cost_head.view", "financials", "cost_head", "view", "View company construction cost heads and mappings.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.cost_head.manage", "financials", "cost_head", "manage", "Create, revise and retire construction cost heads and ledger mappings.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.ledger.view", "financials", "ledger", "view", "View company accounting ledger definitions used for integration and governed postings.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.ledger.manage", "financials", "ledger", "manage", "Create, revise and retire company ledger definitions.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.project_cost.view", "financials", "project_cost", "view", "View project cost entries and allocations.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.project_cost.post", "financials", "project_cost", "post", "Post authoritative project cost entries from approved source records.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.project_cost.adjust", "financials", "project_cost", "adjust", "Create controlled project cost adjustments and reversals.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.site_cash.view", "financials", "site_cash", "view", "View project site-cash accounts and transaction history.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.site_cash.manage", "financials", "site_cash", "manage", "Create and manage project site-cash accounts and advances.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.site_expense.view", "financials", "site_expense", "view", "View site expenses within the authorized project scope.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.site_expense.create", "financials", "site_expense", "create", "Create draft site expenses and cost allocations.", PermissionRisk.MEDIUM),
    ModulePermissionDefinition("financials.site_expense.approve", "financials", "site_expense", "approve", "Approve or reject submitted site expenses.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.site_expense.post", "financials", "site_expense", "post", "Post approved site expenses into site cash and project job cost.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.journal.view", "financials", "journal", "view", "View governed accounting journal entries.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.journal.post", "financials", "journal", "post", "Post or reverse balanced governed accounting journal entries.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.payable.view", "financials", "payable", "view", "View vendor bills, reconciliation and payable state.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.payable.create", "financials", "payable", "create", "Create vendor bill drafts from issued purchase orders.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.payable.manage", "financials", "payable", "manage", "Edit draft vendor bill lines and receipt allocations.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.payable.submit", "financials", "payable", "submit", "Submit reconciled vendor bills for approval.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.payable.approve", "financials", "payable", "approve", "Approve or reject submitted vendor bills.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.payable.override", "financials", "payable", "override", "Override vendor bill reconciliation variances with an explicit reason.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.receivable.view", "financials", "receivable", "view", "View client invoices, receipts and allocations.", PermissionRisk.HIGH),
    ModulePermissionDefinition("financials.receivable.manage", "financials", "receivable", "manage", "Create and issue client invoices linked to commercial certification.", PermissionRisk.CRITICAL),
    ModulePermissionDefinition("financials.receipt.post", "financials", "receipt", "post", "Post and allocate client receipts.", PermissionRisk.CRITICAL),
)
