from dataclasses import dataclass

from app.modules.identity.models import MembershipKind


@dataclass(frozen=True, slots=True)
class RoleTemplateSpec:
    key: str
    name: str
    description: str
    scope_hint: str
    membership_kind_hint: MembershipKind
    permission_keys: frozenset[str]


def _permissions(*keys: str) -> frozenset[str]:
    return frozenset(keys)


INDIA_ROLE_TEMPLATES: tuple[RoleTemplateSpec, ...] = (
    RoleTemplateSpec(
        key="company-management",
        name="Company Management / Director",
        description="Company leadership visibility across projects, reporting, commercial and financial summaries without security administration.",
        scope_hint="company",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "projects.membership.view",
            "reporting.report.view",
            "reporting.report.export",
            "commercial.module.view",
            "commercial.party.view",
            "commercial.wbs.view",
            "commercial.boq.view",
            "commercial.measurement.view",
            "commercial.ra_bill.view",
            "estimating.module.view",
            "estimating.estimate.view",
            "estimating.budget.view",
            "financials.module.view",
            "financials.project_cost.view",
            "financials.site_expense.view",
            "financials.payable.view",
            "financials.receivable.view",
        ),
    ),
    RoleTemplateSpec(
        key="project-manager",
        name="Project Manager",
        description="Project delivery lead with project control, team visibility, field approvals, planning and commercial read access.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "projects.project.update",
            "projects.membership.view",
            "projects.membership.manage",
            "files.file.view",
            "files.file.download",
            "files.file.upload",
            "documents.document.view",
            "drawings.drawing.view",
            "rfis.rfi.view",
            "rfis.rfi.create",
            "rfis.rfi.update",
            "rfis.rfi.respond",
            "submittals.submittal.view",
            "field.daily_report.view",
            "field.daily_report.create",
            "field.daily_report.update",
            "field.daily_report.submit",
            "field.daily_report.approve",
            "workforce.assignment.view",
            "workforce.attendance.view",
            "workforce.attendance.approve",
            "workforce.timecard.view",
            "workforce.timecard.approve",
            "commercial.wbs.view",
            "commercial.boq.view",
            "commercial.measurement.view",
            "commercial.ra_bill.view",
            "scheduling.module.view",
            "scheduling.schedule.view",
            "scheduling.progress.update",
            "reporting.report.view",
        ),
    ),
    RoleTemplateSpec(
        key="site-engineer",
        name="Site Engineer",
        description="Site execution engineer for DPR, drawings, documents, quantities and day-to-day project progress. Commercial rates are intentionally excluded.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "files.file.view",
            "files.file.download",
            "files.file.upload",
            "documents.document.view",
            "drawings.drawing.view",
            "drawings.markup.manage",
            "rfis.rfi.view",
            "rfis.rfi.create",
            "rfis.rfi.update",
            "submittals.submittal.view",
            "field.daily_report.view",
            "field.daily_report.create",
            "field.daily_report.update",
            "field.daily_report.submit",
            "field.dpr.render",
            "workforce.assignment.view",
            "workforce.attendance.view",
            "commercial.wbs.view",
            "scheduling.schedule.view",
            "scheduling.progress.update",
        ),
    ),
    RoleTemplateSpec(
        key="site-supervisor",
        name="Site Supervisor / Foreman",
        description="Field-first role for labour attendance, crew supervision, DPR entry and site evidence. Financial and BOQ commercial values are excluded.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "files.file.view",
            "files.file.upload",
            "drawings.drawing.view",
            "field.daily_report.view",
            "field.daily_report.create",
            "field.daily_report.update",
            "field.daily_report.submit",
            "workforce.assignment.view",
            "workforce.attendance.view",
            "workforce.attendance.create",
            "workforce.attendance.update",
            "workforce.attendance.submit",
            "workforce.timecard.view",
            "workforce.timecard.create",
            "workforce.timecard.update",
            "workforce.timecard.submit",
            "commercial.wbs.view",
        ),
    ),
    RoleTemplateSpec(
        key="qs-billing-engineer",
        name="QS / Billing Engineer",
        description="Quantity surveying, measurement, BOQ, RA billing and estimating responsibilities.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "commercial.module.view",
            "commercial.party.view",
            "commercial.wbs.view",
            "commercial.wbs.manage",
            "commercial.boq.view",
            "commercial.boq.manage",
            "commercial.measurement.view",
            "commercial.measurement.create",
            "commercial.measurement.submit",
            "commercial.ra_bill.view",
            "commercial.ra_bill.create",
            "commercial.ra_bill.submit",
            "estimating.module.view",
            "estimating.estimate.view",
            "estimating.estimate.manage",
            "estimating.rate_analysis.manage",
            "estimating.budget.view",
            "reporting.report.view",
            "reporting.report.export",
        ),
    ),
    RoleTemplateSpec(
        key="planning-engineer",
        name="Planning Engineer",
        description="Planning and progress role for schedules, WBS and project reporting.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "commercial.wbs.view",
            "scheduling.module.view",
            "scheduling.schedule.view",
            "scheduling.schedule.manage",
            "scheduling.progress.update",
            "reporting.report.view",
            "reporting.report.create",
        ),
    ),
    RoleTemplateSpec(
        key="procurement-engineer",
        name="Procurement Engineer",
        description="Purchase requisition, purchase-order and receipt workflow role with supplier visibility.",
        scope_hint="company_project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "commercial.party.view",
            "procurement.module.view",
            "procurement.requisition.view",
            "procurement.requisition.create",
            "procurement.requisition.manage",
            "procurement.requisition.submit",
            "procurement.purchase_order.view",
            "procurement.purchase_order.create",
            "procurement.purchase_order.manage",
            "procurement.purchase_order.submit",
            "procurement.receipt.view",
            "materials.material.view",
            "materials.plan.view",
            "materials.delivery.view",
        ),
    ),
    RoleTemplateSpec(
        key="store-keeper",
        name="Store Keeper",
        description="Site stores role for materials, deliveries, stock locations and consumption records without commercial approvals.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "materials.material.view",
            "materials.plan.view",
            "materials.delivery.view",
            "materials.delivery.manage",
            "materials.consumption.view",
            "materials.consumption.create",
            "materials.inventory.view",
            "materials.inventory.manage",
            "procurement.receipt.view",
            "procurement.receipt.create",
            "procurement.receipt.manage",
        ),
    ),
    RoleTemplateSpec(
        key="safety-ehs-officer",
        name="Safety / EHS Officer",
        description="Site safety, inspections, corrective actions and punch workflow role.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "files.file.view",
            "files.file.upload",
            "safety.module.view",
            "safety.record.view",
            "safety.record.create",
            "safety.record.update",
            "safety.record.close",
            "safety.inspection.view",
            "safety.inspection.create",
            "safety.inspection.execute",
            "safety.punch.view",
            "safety.punch.create",
            "safety.punch.update",
            "field.daily_report.view",
        ),
    ),
    RoleTemplateSpec(
        key="qa-qc-engineer",
        name="QA / QC Engineer",
        description="Quality-oriented document, drawing, submittal, inspection and punch access.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "files.file.view",
            "files.file.download",
            "files.file.upload",
            "documents.document.view",
            "documents.document.create",
            "drawings.drawing.view",
            "drawings.markup.manage",
            "submittals.submittal.view",
            "submittals.submittal.create",
            "submittals.submittal.update",
            "safety.inspection.view",
            "safety.inspection.create",
            "safety.inspection.execute",
            "safety.punch.view",
            "safety.punch.create",
            "safety.punch.update",
        ),
    ),
    RoleTemplateSpec(
        key="document-controller",
        name="Document Controller",
        description="Controlled documents, drawings, RFIs and submittals administration.",
        scope_hint="company_project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "files.file.view",
            "files.file.download",
            "files.file.upload",
            "files.file.manage",
            "documents.document.view",
            "documents.document.create",
            "documents.document.publish",
            "documents.document.manage",
            "drawings.drawing.view",
            "drawings.drawing.revise",
            "drawings.drawing.publish",
            "rfis.rfi.view",
            "submittals.submittal.view",
            "submittals.submittal.create",
            "submittals.submittal.update",
        ),
    ),
    RoleTemplateSpec(
        key="accounts-finance",
        name="Accounts / Finance",
        description="Accounts and project finance role for governed costs, payables, receivables and site expense processing.",
        scope_hint="company_project",
        membership_kind_hint=MembershipKind.INTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "commercial.party.view",
            "commercial.ra_bill.view",
            "financials.module.view",
            "financials.cost_head.view",
            "financials.ledger.view",
            "financials.project_cost.view",
            "financials.site_cash.view",
            "financials.site_expense.view",
            "financials.site_expense.create",
            "financials.payable.view",
            "financials.payable.create",
            "financials.payable.manage",
            "financials.payable.submit",
            "financials.receivable.view",
            "reporting.report.view",
            "reporting.report.export",
        ),
    ),
    RoleTemplateSpec(
        key="client-pmc-reviewer",
        name="Client / PMC Reviewer",
        description="External reviewer for permitted project documents, drawings, RFIs, submittals, DPRs and inspections.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.EXTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "files.file.view",
            "files.file.download",
            "documents.document.view",
            "drawings.drawing.view",
            "rfis.rfi.view",
            "rfis.rfi.respond",
            "submittals.submittal.view",
            "submittals.submittal.review",
            "field.daily_report.view",
            "safety.inspection.view",
            "safety.inspection.review",
        ),
    ),
    RoleTemplateSpec(
        key="consultant-engineer",
        name="Consultant Engineer",
        description="External consultant role focused on drawings, RFIs, submittal reviews and inspections.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.EXTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "files.file.view",
            "files.file.download",
            "documents.document.view",
            "drawings.drawing.view",
            "drawings.markup.manage",
            "rfis.rfi.view",
            "rfis.rfi.respond",
            "submittals.submittal.view",
            "submittals.submittal.review",
            "safety.inspection.view",
            "safety.inspection.review",
        ),
    ),
    RoleTemplateSpec(
        key="subcontractor-engineer",
        name="Subcontractor Engineer",
        description="External subcontractor site engineer for project information, field reporting, RFIs and permitted evidence. Commercial company data is excluded.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.EXTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "files.file.view",
            "files.file.upload",
            "drawings.drawing.view",
            "rfis.rfi.view",
            "rfis.rfi.create",
            "field.daily_report.view",
            "field.daily_report.create",
            "field.daily_report.update",
            "field.daily_report.submit",
            "commercial.wbs.view",
        ),
    ),
    RoleTemplateSpec(
        key="labour-contractor-supervisor",
        name="Labour Contractor Supervisor",
        description="External labour-contractor supervisor for assigned-project attendance and daily field reporting without company commercial visibility.",
        scope_hint="project",
        membership_kind_hint=MembershipKind.EXTERNAL,
        permission_keys=_permissions(
            "projects.project.view",
            "field.daily_report.view",
            "field.daily_report.create",
            "field.daily_report.update",
            "field.daily_report.submit",
            "workforce.assignment.view",
            "workforce.attendance.view",
            "workforce.attendance.create",
            "workforce.attendance.update",
            "workforce.attendance.submit",
        ),
    ),
)

ROLE_TEMPLATES_BY_KEY = {template.key: template for template in INDIA_ROLE_TEMPLATES}
